Don't use print for graphql check
intuit/lean-schema pull request #2
Opened 2020-02-04 21:27 UTC by hplewis

We don't need to print out the json in order to check it. This improves
runtimes significantly on larger files.

Before this change, we consistently got around 2.9 seconds on a 45M
graphql.json file.

```
real    0m2.894s
user    0m2.635s
sys     0m0.256s
```

After this change, we are consistently getting around 1.8 seconds on the
same 45M file.

```
real    0m1.808s
user    0m1.561s
sys     0m0.252s
```

This has been checked and invalid files still fail.

2020-02-04 22:27 UTC, hplewis commented
Oh and this also now checks for valid files with either

`.data.__schema` (old check)
OR
`.__schema`

Since that can also be valid.

2020-02-04 23:27 UTC, per06a requested changes
Just change to use arparse and all good

2020-02-04 23:27 UTC, per06a commented on check_graphqljson.py
> +        usage()
Just use `arparse` for this sort of thing, you get usage/help for free. See the get_types.py and decomp.py files for examples

2020-02-05 18:41 UTC, per06a approved these changes

2020-02-05 18:41 UTC, merged